apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: reverse-proxy
  name: reverse-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: reverse-proxy
    spec:
      containers:
      - image: mostafaelfekky/reverse-proxy
        name: reverse-proxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always
